version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mymonitor:1.0.0
    container_name: mymonitor_app
    env_file: .env
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - 3000:3000
    entrypoint: /tmp/entrypoint.sh
    command: ["php", "-t", "./public/", "-S", "0.0.0.0:3000"]

  db:
    image: mysql:8.0.23
    container_name: mymonitor_db
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
  db_data:
